# Generated by Django 3.0.8 on 2020-12-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
                ('category', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('slots', models.DateTimeField()),
                ('tables', models.CharField(max_length=5)),
            ],
        ),
    ]
