# Generated by Django 3.0.8 on 2020-12-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
