# Generated by Django 3.0.8 on 2020-12-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201231_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmodel',
            name='slots',
            field=models.CharField(choices=[('10PM', '10PM'), ('11PM', '11PM'), ('12PM', '12PM'), ('1PM', '1PM')], default='Select-Slot', max_length=12),
        ),
    ]
