# Generated by Django 3.0.8 on 2020-12-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201231_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmodel',
            name='slots',
            field=models.CharField(choices=[('6PM', '6PM'), ('7PM', '7PM'), ('8PM', '8PM'), ('9PM', '9PM'), ('10PM', '10PM'), ('11PM', '11PM'), ('12PM', '12PM')], max_length=12),
        ),
    ]
