# Generated by Django 3.0.8 on 2020-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20201231_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsmodel',
            name='tables',
        ),
        migrations.AddField(
            model_name='restaurantsmodel',
            name='tableNumber',
            field=models.CharField(choices=[('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurantsmodel',
            name='slots',
            field=models.CharField(choices=[('6PM', '6PM'), ('7PM', '7PM'), ('8PM', '8PM'), ('9PM', '9PM'), ('10PM', '10PM'), ('11PM', '11PM'), ('12PM', '12PM')], default='10PM', max_length=12),
        ),
    ]
