# Generated by Django 3.0.8 on 2021-01-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='alternate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
