# Generated by Django 3.0.8 on 2021-01-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210102_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(choices=[('6PM to 7PM', '6PM to 7PM'), ('7PM to 8PM', '7PM to 8PM'), ('8PM to 9PM', '8PM to 9PM'), ('9PM to 10PM', '9PM to 10PM'), ('10PM to 11PM', '10PM to 11PM'), ('11PM to 12PM', '11PM to 12PM'), ('12PM to 1PM', '12PM to 1PM')], default='10PM', max_length=12)),
                ('tableNumber', models.CharField(choices=[('7', '7'), ('6', '6'), ('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='1', max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='restaurantsmodel',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='restaurantsmodel',
            name='tableNumber',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='Restaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.RestaurantsModel'),
        ),
    ]
