# Generated by Django 3.0.8 on 2021-01-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210102_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmodel',
            name='category',
            field=models.CharField(choices=[('Pure-Veg', 'Pure-Veg'), ('Non-Veg', 'Non-Veg'), ('Veg-NonVeg', 'Veg-NonVeg')], default='Pure-Veg', max_length=15),
        ),
    ]
