# Generated by Django 3.0.8 on 2021-01-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='Restaurants',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.RestaurantsModel'),
            preserve_default=False,
        ),
    ]
