# Generated by Django 3.0.8 on 2021-01-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_ratingmodel_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsmodel',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.RatingModel'),
            preserve_default=False,
        ),
    ]
