# Generated by Django 3.0.8 on 2021-01-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_restaurantsmodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsmodel',
            name='rating',
        ),
    ]
