# Generated by Django 3.0.8 on 2021-01-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_restaurantsmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantsmodel',
            name='rating',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='App.RatingModel'),
            preserve_default=False,
        ),
    ]
