# Generated by Django 3.0.8 on 2021-01-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20210104_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsmodel',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, max_length=5),
        ),
    ]
