# Generated by Django 3.0.8 on 2021-01-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20210104_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsmodel',
            name='rating',
        ),
    ]
