# Generated by Django 3.0.8 on 2021-01-04 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20210104_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='Bookingdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
